add_cflags = -I../include

cxxsources = \
	../src/divide.cpp \
	../src/multiply.cpp \
	../src/hybrid.cpp

csources = \
	../src/add.c \
	../src/subtract.c

sources = $(cxxsources) $(csources)

include ../makefile